# Generated by Django 4.2.21 on 2025-05-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='nieznany', max_length=100),
        ),
    ]
