# Generated by Django 4.2.21 on 2025-05-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0004_book_image_alter_book_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
