# Generated by Django 4.2.21 on 2025-05-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0006_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
